# Generated by Django 5.1.6 on 2025-02-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('cooking_time', models.CharField(max_length=50)),
                ('ingredients', models.TextField()),
                ('date_published', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
